package com.ftn.sbnz.model.cocktail;

public enum Glass {
    BEER_MUG,
    CHAMPAGNE_FLUTE,
    COFFEE_MUG,
    COPPER_MUG,
    COLLINS_GLASS,
    COUPE_GLASS,
    HURRICANE_GLASS,
    IRISH_COFFEE_CUP,
    MARGARITA_GLASS,
    MARTINI_GLASS,
    NICK_AND_NORA_GLASS,
    PINT_GLASS,
    PITCHER,
    POUSSE_CAFE_GLASS,
    PUNCH_BOWL,
    SHOT_GLASS,
    WHISKEY_GLASS,
    WHITE_WINE_GLASS,

}
