package rules.menu;
import com.ftn.sbnz.model.inventory.*;
import com.ftn.sbnz.model.cocktail.*;
import com.ftn.sbnz.model.preference.*;
import com.ftn.sbnz.model.event.*;

import org.drools.core.spi.KnowledgeHelper;
import java.util.*;


rule "GetOrdersInLastFifteenMinutes"
salience(10)
when
    $cocktails: List() from accumulate(
        OrderEvent($cocktail: cocktail) over window: time(15m),
        collectList($cocktail)
    )
then
    CocktailListWrapper c=new CocktailListWrapper($cocktails);
    c.cocktailNumWithAlcoholStrength();
    insert(c);
end


rule "AddFirstStrongPreference"
salience(10)
when
    CocktailListWrapper($numOfStrongCocktails: getStrongCocktailsNumber())
    not( AlcoholAmountPreference(isStrong()))
    eval($numOfStrongCocktails>0)
then
    insert(new AlcoholAmountPreference(AlcoholStrength.STRONG));
end


rule "AddOtherStrongPreference"
salience(10)
when
    CocktailListWrapper($numOfStrongCocktails: getStrongCocktailsNumber())
    $count: Long() from accumulate(
            AlcoholAmountPreference(isStrong()),
            count(1)
        )
    eval($count<$numOfStrongCocktails)
then
    insert(new AlcoholAmountPreference(AlcoholStrength.STRONG));
end


rule "AddFirstLightPreference"
salience(10)
when
    CocktailListWrapper($numOfLightCocktails: getLightCocktailsNumber())
    not(AlcoholAmountPreference(isLight()))
    eval($numOfLightCocktails>0)
then
    insert(new AlcoholAmountPreference(AlcoholStrength.LIGHT));
end


rule "AddOtherLightPreference"
salience(10)
when
    CocktailListWrapper($numOfLightCocktails: getLightCocktailsNumber())
    $count: Long() from accumulate(
            AlcoholAmountPreference(isLight()),
            count(1)
        )
    eval($count<$numOfLightCocktails)
then
    insert(new AlcoholAmountPreference(AlcoholStrength.LIGHT));
end



rule "AddFirstMediumPreference"
salience(10)
when
    CocktailListWrapper($numOfMediumCocktails: getMediumCocktailsNumber())
    not(AlcoholAmountPreference(isMedium()))
    eval($numOfMediumCocktails > 0)
then
    insert(new AlcoholAmountPreference(AlcoholStrength.MEDIUM));
end


rule "AddOtherMediumPreference"
salience(10)
when
    CocktailListWrapper($numOfMediumCocktails: getMediumCocktailsNumber())
    $count: Long() from accumulate(
            AlcoholAmountPreference(isMedium()),
            count(1)
        )
    eval($count < $numOfMediumCocktails)
then
    insert(new AlcoholAmountPreference(AlcoholStrength.MEDIUM));
end


rule "DeleteCocktailListWrapper"
salience(5)
when
    $wrapper: CocktailListWrapper()
    $count: Long() from accumulate(
            AlcoholAmountPreference(),
            count(1)
        )
    eval($count >= 10)
then
    delete($wrapper);
end


rule "AddCocktail"

when
    $glassPreference: GlassPreference($glass: glass)
    $alcoholAmountPreference: AlcoholAmountPreference($alcoholStrength: alcoholStrength)
    $cocktail: Cocktail(glass == $glass, alcoholStrength == $alcoholStrength)
    $event: Event(doesNotContain($cocktail))
then
    delete($glassPreference);
    delete($alcoholAmountPreference);

    modify($event){addCocktailToMenu($cocktail)}
end
